### PR TITLE
Improve import

### PR DESCRIPTION
**Pull request by alexhauser**
**Description:**

Small import improvements

**Changes:**
- On `ImportActivity`, start the import when hitting "Done" on the soft keyboard after entering the identity password instead of only focussing the "Import" button
- Center-align the text box for the textual identity in `ImportActivity`
- Add hero icon to `ImportOptionsActivity`

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Screenshot_2019-08-07-21-30-41

**Comment by kalaspuffar** [comment]
Hi, @alexhauser and good morning :)

I was probably too tired yesterday so did not leave a comment. It seems like we need to have an option of scrolling in landscape mode. Maybe we need it in portrait as well, the textual version of the identity can be at least up to 15 lines. (Counted a rekeyed identity).

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

good catch Daniel, and good morning to you, too! 
I will post a commit fixing this asap.

Best regards,
Alex

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

this should fix it. I have noticed some more landscape quirks on smaller resolutions along the way, which I will address separately.

Have a great day,
Alex

**Pull request merged**
