### PR TITLE
Fix strength meter dark mode and display issues

### PR DESCRIPTION
**Pull request by alexhauser**
Issue #306.

Description:
Strength meter font was unreadable in dark mode.

Changes:
Set fixed font color for strength meter components.

### CODE REVIEW

**Comment by alexhauser** [comment]
Hi @kalaspuffar , please wait with merging this, I'll also add a commit for the layout bugfix (issue #308) shortly. Thanks.

**Comment by alexhauser** [comment]
Ok, display bug fix is now included. Review would be appreciated, thanks.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I've looked at the pull request and the main issue I have with this one is the extra dependency. Adding extra libraries for layout seems strange. Could we do the same things with the constrained layout? Or perhaps a linear layout?

Best regards
Daniel

**Comment by kalaspuffar** [comment]
Hi again.

I think that if we can find a good solution to this one then I want to build a release. We have a good amount of new stuff that we want to push.

Best regards
Daniel

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

i know it's rediculous, but apparently neither `ConstraintLayout` nor `LinearLayout` nor any other "built-in" `ViewGroup` containers support wrapping its children to the next line. At least that's the conclusion I ended up with researching a solution. Anybody please correct me if I'm wrong.

It seems the only two options here are either pulling in Google's FlexBox layout or writing our own ViewGroup-derived layout class.

I opted for using the well-tested and proven Google solution instaed of rolling my own. But if you prefer writing our own `ViewGroup` class and getting rid of the dependency, I can certainly do so. 

Please let me know how to proceed.

Thanks and best regards,
Alex

**Pull request merged**
