### PR TITLE
WIP: Show identity name in the ActionBar of SimplifiedActivity

### PR DESCRIPTION
**Pull request by janneoksanen**
Issue #220 
feat: make current identity visible on main login screen

Description:
Shows currently used identity name on the ActionBar of SimplifiedActivity

screenshot_20190301-151542

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi @janneoksanen 

Great work, this seems like a good quick fix for the issue. Not super clear that the information is found in the app bar. Don't know if I've seen this solution in any other app. I was thinking like a quick fix to add a panel to the icon with some text. Like in this wireframe.

https://s3.amazonaws.com/assets.mockflow.com/app/wireframepro/company/Cc09d9f00343be5aa571cc840f3472f46/projects/Mf421dde088ed6d581c66618009e730f21551597018478/pages/e80320270a0c4609a49206bd7ebe9c09/image/e80320270a0c4609a49206bd7ebe9c09.png

I would like someone to create a good design for these pages though so we don't do too many design changes that require new text strings that translators need to translate.

What do you think, shall I add your merge request in the meantime even though it's not the final solution?

Best regards
Daniel

**Comment by janneoksanen** [comment]
Hi Daniel, 

I'll do it according to the wireframe so we don't have to go back and fix the fix.

Janne

**Comment by janneoksanen** [comment]
How about something like this?

screenshot_20190308-110937

**Comment by kalaspuffar** [comment]
Hi Janne

Great work, not sure if we want to introduce another blue color. Maybe we should keep it simple with black on white instead.

Not looked at the code yet, but I will as soon as time permits.

Best regards
Daniel

**Comment by kalaspuffar** [comment]
I added the WIP (work in progress) to the title just to see when the pull request is ready for review. Please remove when you are done and add it back if you work on the issue so I know the status.

**Pull request closed without merging**
