### PR TITLE
First implementation of startup guide.

### PR DESCRIPTION
**Pull request by kalaspuffar**
Issue #435.

Description:
This is my first implementation of some new startup screens with less text and more graphics, welcoming you into the application.

Changes:
Added wizard screens and removed the old startup screen. Kept the startup screen logic to make the transition as easy as possible.
Screenshot_20200318-230728
Screenshot_20200318-230806
Screenshot_20200318-230814
Screenshot_20200318-230824
Screenshot_20200318-230831
Screenshot_20200318-230836
Screenshot_20200318-230840

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

As you are a native German speaker and the Germanic languages, Swedish included could be hard to handle in text as some words may wrap strangely and so on could you create and test a German version before I merge this change?

I've tested the swedish translation and that seems to work. Will try the Mandarin one today as well.

Best regards
Daniel

**Comment by alexhauser** [comment]
Sure, I'll give it a go as soon as I have some time at hand.

**Comment by alexhauser** [comment]
@kalaspuffar, German seems to work just fine on decent resolutions. Here is the German translation if you want to try it yourself, or if you want to include it into the merge:

```XML
<string name="intro_1">Willkommen zu</string>
<string name="intro_2">SQRL ist _eine_ Identität.\n\nEs erstellt _eindeutige_ Schlüssel für jede Webseite.\n\nUnd enthüllt keine _nachverfolgbaren_ Daten.</string>
<string name="intro_3">Diese App ist _Open Source_ Software und steht unter einer _offenen Lizenz_.\n\nMehr dazu im Menüpunkt _Über_ direkt in der App.</string>
<string name="intro_4">Starten Sie, indem Sie eine Identität _erzeugen_ oder _importieren_.</string>
<string name="wizard_skip">Überspringen</string>
<string name="wizard_next">Weiter</string>
```

However, I've noticed that we do have a general problem on small resolutions:

480x800_1

480x800_2

Some kind of scaling would be needed here it seems.

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Great catch, changing text size due to screen size is a bit tricky, but there is a new auto-scaling feature that seems to work fine except it might create huge text :)

And the first page with so many text boxes is hard to get scaling correctly. Please try again, and if the first page still has a problem, you are welcome to give it a try. I'm not sure how to improve that page.

Best regards
Daniel

**Pull request merged**
