### PR TITLE
Add scan qr icon and associated button

### PR DESCRIPTION
**Pull request by sengsational**
Issue #252  Improve login experience
Description:
Created an icon and associated button on mail activity.'

Changes:
Added `<Button...` which uses a new vector graphic icon of a magnifying glass aiming at a simplified QR code.
button with icon

Notes:
This change was as much for training me how to use the source control that's integrated with Android Studio as anything.  I have no doubt that there's some "real" UI people out there that will give us guidelines, but we could use this in the mean time.

### CODE REVIEW

**Comment by sengsational** [comment]
Changed from `<Button...` to `AppCompatButton...` and also had to remove `android:drawableLeft...` since that causes problems on older versions of the OS.

**Comment by kalaspuffar** [comment]
I added the WIP (work in progress) to the title just to see when the pull request is ready for review. Please remove when you are done and add it back if you work on the issue so I know the status.

**Comment by sengsational** [comment]
This is not a part of the comprehensive UI update, but might make it more clear for new users what to do on the simplified activity home screen.

**Comment by sengsational** [comment]
Fixed a small syntax error in the layout.

**Pull request merged**
