### PR TITLE
Better alt-id and account options

### PR DESCRIPTION
**Pull request by alexhauser**
Issue #379.

This one looks a little scarier than it actually is, mainly due to some refactorings that I've done along the way. Still, sorry for the rather large PR, but I hope you'll agree that it's worth it in the end.

**Description:**

Move alternate-id as well as account options (disable, enable and remove) to the main login flow. 

This solves the issue that none of the account options could previously be used together with an alt-id. Also, it enables using QuickPass for any operation that doesn't require the RescueCode. 

Lastly, this should improve user-friendliness as well as maintainability, since we now have all the login-related code in one place.

**Changes:**

- Add an (initially collapsed) area called "advanced functions" to the login window
This contains the text field for the alt-id as well as all the account-related options
- Add an (initially hidden) rescue code input form to the login window
This will be shown instead of the password field on operations that need the RescueCode
- Add help icons to all advanced functions, providing user guidance
- Rename `UrlLoginActivity` to `LoginActivity`
- Remove the now obsolete activities 
    - `AlternativeLoginActivity`
    - `AccountOptionsActivity`
    - `DisableAccountActivity`
    - `EnableAccountActivity`
    - `RemoveAccountActivity`
- Adapt `EnableQuickPassActivity` to the new layout of `LoginActivity`

When testing this, please note  that issue #371 is still open, so the app needs to be reset after disabling an account, otherwise all the following actions will fail.

Here are some screenshots of the new login window, when advanced functions are expanded:

Light mode, operation requiring only the password:

Light mode, operation requiring the RescueCode:

Dark mode, operation requiring only the password:

Dark mode, operation requiring the RescueCode:

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

I ran the PR now when I'm back at the keyboard. And found the following strang background on the identity name. 

And if you click on advanced options the description text is removed. Perhaps that is intentional but it as a user it is something you notice and wonder why. The text will not return if you press the advanced options again and close that menu.

Will look at the PR code more closely this evening.

Best regards
Daniel

background-issue

**Comment by kalaspuffar** [comment]
decription-shown

**Comment by alexhauser** [comment]
Hi @kalaspuffar,

thanks for running the PR and commenting.

The background behind the identity name is weird, I haven't seen this in my testing, but I will investigate.

Hiding the description (and not showing it again) was intentional, but can be discussed of course. I figured anyone using advanced features wouldn't need the description anyway, and we can use the screen real estate. But I'm completely open for changes here!

Best regards,
Alex

**Comment by alexhauser** [comment]
By the way, I cheated a little on the accessibility front on this one, since making every radio button 48dp high would have bloated the layout a lot. But this is also something that can be discussed of course.

**Comment by alexhauser** [comment]
Hi @kalaspuffar ,

I just wanted to let you know that while testing, I "accidently" found out what the gray background that you had experienced on some controls a while back is actually all about: It's simply **input focus**. 

When we are testing with the emulator and using the physical keyboard, Android leaves "touch mode" and enables input focus on controls. I noticed by chance that, when switching through controls with the tab key on the physical keyboard, some touch-enabled `TextView`s would get input focus, which is indicated by displaying a light gray background on the control. 

So this is in fact "intended behaviour" and we can erase this mistery from the back of our heads. 😉

Non the less, I will set a few `android:focusable="false"` attributes where input focus is not needed (as for example on the identity name in the identity selector, since we still have the icon which can be focussed in non-touch-mode, and this does not affect that it can be tapped/clicked).

Best regards,
Alex

**Comment by kalaspuffar** [comment]
Hi @alexhauser 

Awesome catch. Great work, it was something that annoyed me even though it wasn't important but having a reason feels much better.

Thanks
Daniel

**Pull request merged**
